### PR TITLE
Issue #222: Adding versions to resources in CSV

### LINKED ISSUE #222: Add versions to resources to fix CSV validation errors
## Bug Report
The CSV (v0.7.0) for the Open Liberty operator is missing the `version` field for each of the resources listed under the "owned" CRDs.  This is apparently a required field now.

### What did you do?
Tried doing an `oc create -f` against a file like this and it failed.

### What did you expect to see?

It should have installed without errors.

### What did you see instead?

From my own operator where I did the same thing:

error validating "stocktrader-operator.v0.1.0.clusterserviceversion.yaml": error validating data: [ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[0]): missing required field "version" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[1]): missing required field "version" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[2]): missing required field "version" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[3]): missing required field "version" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[4]): missing required field "version" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[5]): missing required field "version" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[6]): missing required field "version" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources]; if you choose to ignore these errors, turn validation off with --validate=false

### Environment

* Kubernetes version information: 

OCP 4.5

* OpenShift version information (if applicable):

OCP 4.5

* Appsody CLI version (if applicable):

n/a

* Appsody Stack (if applicable):

n/a

### Possible solution

Add the `version` tag to each resource in the list.

### Additional context

Discussed with the Liberty team on Slack prior to opening: https://ibm-cloud.slack.com/archives/C32494NQ6/p1613752325141300

image

### PR DESCRIPTION
**Pull request by halim-lee**
**What this PR does / why we need it?**:

- Version tag for resources in CSV is required

**Does this PR introduce a user-facing change?**

- [ ] User guide
- [ ] `CHANGELOG.md`

**Which issue(s) this PR fixes**:

Fixes #222

### CODE REVIEW

File: api/v1beta1/openlibertyapplication_types.go [hunk 1]
```diff
@@ -441,6 +441,7 @@ const (
 // +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Reconciled')].message",priority=1,description="Failure message from reconcile condition"
 // +kubebuilder:printcolumn:name="DependenciesSatisfied",type="string",JSONPath=".status.conditions[?(@.type=='DependenciesSatisfied')].status",priority=1,description="Status of the application dependencies"
 // +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0,description="Age of the resource"
+//+operator-sdk:csv:customresourcedefinitions:displayName="Open Liberty Application",resources={{Deployment,v1,},{Service,v1,},{StatefulSet,v1,},{Route,v1,},{HorizontalPodAutoscaler,v1,}}
```
Comment (leochr) [inline api/v1beta1/openlibertyapplication_types.go:444]: Let's add ServiceAccount and Secret to the list. Both have v1 as the version.
Minor thing, but it'll be good to remove the `,` after v1 to improve readability. 

Let's change to use the CR name as display name: OpenLibertyApplication - same for trace and dump CRs

**Review by leochr — COMMENTED** [review]
@halim-lee Thanks for the PR. Added some comments.

**Review by leochr — APPROVED** [review]
Looks good. Thanks @halim-lee
